using Unity.Burst;
using Unity.Collections;
using Unity.Mathematics;

/// <summary>
/// Represents a chunk of voxel terrain, containing data for rendering and collision.
/// Designed to be used in high-performance jobs compiled with the Burst Compiler.
/// This is a C# translation of the Godot C++ class 'JarVoxelChunk'.
/// </summary>
[BurstCompile]
public unsafe struct JarVoxelChunk
{
    // C# doesn't have a direct equivalent of Godot's scene tree nodes
    // for use inside a Burst-compatible struct. Instead of holding references to
    // wrapper objects like MeshInstance3D, we would hold pointers or IDs to the
    // raw data (e.g., mesh data, physics body data).

    #region Fields

    /// <summary>
    /// Pointer to the mesh data associated with this chunk. In a real application,
    /// this might be a handle or an ID into a central mesh data manager.
    /// </summary>
    public void* MeshData;

    /// <summary>
    /// Pointer to the collision shape data.
    /// </summary>
    public void* CollisionShapeData;

    /// <summary>
    /// Pointer to the static physics body data.
    /// </summary>
    public void* StaticBodyData;

    /// <summary>
    /// A list of pointers or handles to detail instance data (e.g., for grass, rocks).
    /// Replaces the std::vector<MultiMeshInstance3D*> from the C++ class.
    /// This must be initialized and disposed of by an external manager.
    /// </summary>
    public NativeList<long> MultiMeshInstances;

    /// <summary>
    /// A pointer to the raw mesh data generated by the voxel meshing algorithm.
    /// This is used to update the collision shape asynchronously.
    /// </summary>
    public ChunkMeshData* ChunkMeshData;

    /// <summary>
    /// The current level of detail for this chunk.
    /// </summary>
    public int Lod;

    /// <summary>
    /// The LOD level at or below which a physics collider will be generated.
    /// </summary>
    public int ColliderLodThreshold;

    /// <summary>
    /// A bitmask indicating which boundaries of the chunk have a lower-LOD neighbor.
    /// </summary>
    public byte Boundaries;

    /// <summary>
    /// A flag indicating if this chunk is on the edge of the rendered volume.
    /// </summary>
    public bool IsEdgeChunk;

    /// <summary>
    /// The world-space bounding box of this chunk.
    /// </summary>
    public BurstBounds Bounds;

    /// <summary>
    /// The world-space position of this chunk's center.
    /// </summary>
    public float3 Position;

    #endregion

    #region Methods

    /// <summary>
    /// Updates the list of detail multi-mesh instances to a new count.
    /// This mirrors the logic of _update_multi_mesh_instances.
    /// </summary>
    /// <param name="newCount">The desired number of multi-mesh instances.</param>
    public void UpdateMultiMeshInstances(int newCount)
    {
        int currentCount = MultiMeshInstances.Length;
        if (currentCount == newCount)
        {
            return;
        }

        if (currentCount < newCount)
        {
            // In a real implementation, we would add new instance handles/pointers.
            // Here we just add default values to resize the list.
            for (int i = currentCount; i < newCount; i++)
            {
                MultiMeshInstances.Add(0); // Placeholder for a new instance handle.
            }
        }
        else // currentCount > newCount
        {
            // Remove instances from the end.
            // External code would be responsible for freeing the associated resources.
            MultiMeshInstances.Resize(newCount, NativeArrayOptions.UninitializedMemory);
        }
    }

    /// <summary>
    /// Updates the chunk's mesh, collision, and detail data based on new mesh data.
    /// This is the C# equivalent of the 'update_chunk' method.
    /// </summary>
    /// <param name="terrain">A pointer to the parent terrain data.</param>
    /// <param name="node">A pointer to the octree node this chunk belongs to.</param>
    /// <param name="chunkMeshData">The new mesh data for the chunk.</param>
    /// <returns>A boolean indicating if a collider update is required.</returns>
    public bool UpdateChunk(ref JarVoxelTerrain terrain, VoxelOctreeNode* node, ChunkMeshData* chunkMeshData)
    {
        this.ChunkMeshData = chunkMeshData;

        // In C++, Ref<T> objects were used. Here, we assume the chunk holds raw pointers
        // or handles to mesh, collider, and material data, which are managed externally.
        // e.g., MeshData = ...; CollisionShapeData = ...;

        Lod = chunkMeshData->Lod;
        Boundaries = chunkMeshData->Boundaries;
        IsEdgeChunk = chunkMeshData->EdgeChunk;
        Bounds = chunkMeshData->Bounds;
        Position = Bounds.Center;

        // The actual mesh update (clearing and adding surfaces) would be handled by
        // an external rendering system using the data from chunkMeshData->MeshArray.
        // This struct's role is to hold the data and state.

        bool colliderUpdateRequired = false;
        bool generateCollider = Lod <= ColliderLodThreshold;

        if (generateCollider)
        {
            // Instead of enqueuing the update directly, we signal to the calling system
            // that this chunk needs its collider rebuilt.
            colliderUpdateRequired = true;
        }

        // The external system would check 'colliderUpdateRequired'. If true, it schedules
        // a job to call UpdateCollisionMesh(). If false, it disables the collider component.

        return colliderUpdateRequired;
    }


    /// <summary>
    /// Prepares the collision faces data from the cached ChunkMeshData.
    /// An external physics system would use the returned NativeArray to build the physics mesh.
    /// This corresponds to the 'update_collision_mesh' method.
    /// </summary>
    /// <returns>A NativeArray of vectors representing the triangle faces for the collider.</returns>
    public NativeArray<float3> CreateCollisionMesh(Allocator allocator)
    {
        if (ChunkMeshData == null)
        {
            return new NativeArray<float3>(0, allocator);
        }

        // This call is a placeholder for the logic inside
        // _chunk_mesh_data->create_collision_mesh()
        return this.ChunkMeshData->CreateCollisionMesh(allocator);
    }


    /// <summary>
    /// Frees any native collections owned by this struct.
    /// Must be called before the struct is destroyed.
    /// </summary>
    public void Dispose()
    {
        if (MultiMeshInstances.IsCreated)
        {
            MultiMeshInstances.Dispose();
        }
    }

    #endregion
}