using UnityEngine;

// This component is the C# equivalent of your JarVoxelChunk class.
// It manages the mesh and visual representation of a single voxel chunk.
[RequireComponent(typeof(MeshFilter), typeof(MeshRenderer))]
public class VoxelChunk : MonoBehaviour
{
    private MeshFilter meshFilter;
    private MeshRenderer meshRenderer;
    private Mesh chunkMesh;

    // Public properties to hold chunk data, similar to the C++ version.
    public int Lod { get; private set; }
    public bool IsEdgeChunk { get; private set; }
    public Bounds Bounds { get; private set; }

    private void Awake()
    {
        // Get the required components and create a new mesh object for this chunk.
        meshFilter = GetComponent<MeshFilter>();
        meshRenderer = GetComponent<MeshRenderer>();
        chunkMesh = new Mesh();
        meshFilter.mesh = chunkMesh;
    }

    /// <summary>
    /// This method is the C# equivalent of `update_chunk` from your C++ file.
    /// It takes the generated mesh data and applies it to the chunk's mesh filter.
    /// </summary>
    /// <param name="chunkMeshData">The mesh data generated by the meshing job.</param>
    /// <param name="material">The material to apply to the chunk.</param>
    public void UpdateChunk(ChunkMeshData chunkMeshData, Material material)
    {
        // For simplicity, Lod, IsEdgeChunk, and Bounds are not fully implemented
        // as the core task is to display the mesh. They are here for future use.
        // Lod = chunkMeshData.lod;
        // IsEdgeChunk = chunkMeshData.edge_chunk;
        // Bounds = chunkMeshData.bounds;

        // Set the position of the chunk's GameObject.
        // transform.position = Bounds.center;

        // Clear any existing mesh data and apply the new data.
        chunkMesh.Clear();
        chunkMesh.SetVertices(chunkMeshData.Vertices.AsArray());
        chunkMesh.SetIndices(chunkMeshData.Indices.AsArray(), MeshTopology.Triangles, 0);
        chunkMesh.SetNormals(chunkMeshData.Normals.AsArray());

        // Recalculate bounds and apply the material.
        chunkMesh.RecalculateBounds();
        meshRenderer.material = material;
    }

    // A method to clean up the mesh when the chunk is destroyed.
    private void OnDestroy()
    {
        if (chunkMesh != null)
        {
            Destroy(chunkMesh);
        }
    }
}